# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/socrates/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),socrates)

$(call add-radio-file-sha1-checked,radio/abl.img,40ee2d1f64d60a778e2b2f45d5024546bbe35f90)
$(call add-radio-file-sha1-checked,radio/aop.img,54514359c1a40ba4132f137acd60f55da7499d91)
$(call add-radio-file-sha1-checked,radio/aop_config.img,bb487d83a6010cbcbedba9d4455e12a5aa0e093e)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,8b8d9645c30e0e99266c22902973dc173d6533eb)
$(call add-radio-file-sha1-checked,radio/cpucp.img,98421250334daa72078735780f846fce83012340)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3788428b0ae6b8af7d7fd3d0c4a9635ac352b088)
$(call add-radio-file-sha1-checked,radio/dsp.img,549e0f0cb9ccb001df3e10981b465f48e6f57a8f)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e53852349381fbb1ed8d58ac9434ff680726b7fe)
$(call add-radio-file-sha1-checked,radio/hyp.img,cdc3e45e08df606e2769d45d5c391e4824e6bcbc)
$(call add-radio-file-sha1-checked,radio/imagefv.img,c0dd6c80376a684ddffbd4e8dffb92b542d8d2a7)
$(call add-radio-file-sha1-checked,radio/keymaster.img,2baea5e222b3ad3cdd91932fa02af9e30d20e179)
$(call add-radio-file-sha1-checked,radio/modem.img,f391ba25c4735193c3f65676b02a625f6d611eb6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ca300c7f0a655d7d92fd3c884c69abe40d0bf134)
$(call add-radio-file-sha1-checked,radio/shrm.img,712a8225196f93a8c3f494a39279ec68c7ba0a77)
$(call add-radio-file-sha1-checked,radio/tz.img,dc87cb7687133ff49dc5d4cdc04dbe4a80c059a2)
$(call add-radio-file-sha1-checked,radio/uefi.img,41a6ab8b4b001b9905cd88dc7bb4307e2b4f7b92)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e51bbb05c4bb9f902b06e109f1f3404d3c48de90)
$(call add-radio-file-sha1-checked,radio/xbl.img,6c6c37b9eb5725152452cdd1183ec462eb3ab7f8)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,6869fb0354bc99ace83d86c104ee2e664d686a2b)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,c868f1efef52033909db246848fcff98bd016601)

endif
